-
  code: 
    - 77
    - 97
    - 99
    - 177
    - 197
    - 199
    - 777
    - 799
  title: Москва
-
  code: 
    - 78
    - 178
    - 98
  title: Санкт-Петербург
-
  code: 
    - 22
  title: Алтайский край
-
  code: 
    - 28
  title: Амурская обл.
-
  code: 
    - 28
  title: Амурская обл.
-
  code: 
    - 29
  title: Архангельская обл.
-
  code: 
    - 30
  title: Астраханская обл.
-
  code: 
    - 2
    - 102
  title: Башкортостан
-
  code: 
    - 31
  title: Белгородская обл.
-
  code: 
    - 32
  title: Брянская обл.
-
  code: 
    - 33
  title: Владимирская обл.
-
  code: 
    - 34
    - 134
  title: Волгоградская обл.
-
  code: 
    - 35
  title: Вологодская обл.
-
  code: 
    - 36
    - 136
  title: Воронежская обл.
-
  code: 
    - 79
  title: Еврейская автономная обл.
-
  code: 
    - 75
    - 80
  title: Забайкальский край
-
  code: 
    - 37
  title: Ивановская обл.
-
  code: 
    - 38
    - 138
    - 85
  title: Иркутская обл.
-
  code: 
    - 7
  title: Кабардино-Балкарская Республика
-
  code: 
    - 39
    - 91
  title: Калининградская обл.
-
  code: 
    - 40
  title: Калужская обл.
-
  code: 
    - 41
  title: Камчатский край
-
  code: 
    - 9
  title: Карачаево-Черкесская Республика
-
  code: 
    - 42
    - 142
  title: Кемеровская обл.
-
  code: 
    - 43
  title: Кировская обл.
-
  code: 
    - 44
  title: Костромская обл.
-
  code: 
    - 23
    - 93
    - 123
  title: Краснодарский край
-
  code: 
    - 24
    - 124
    - 84
    - 88
  title: Красноярский край
-
  code: 
    - 45
  title: Курганская обл.
-
  code: 
    - 46
  title: Курская обл.
-
  code: 
    - 47
  title: Ленинградскя обл.
-
  code: 
    - 48
  title: Липецкая обл.
-
  code: 
    - 49
  title: Магаданская обл.
-
  code: 
    - 50
    - 90
    - 150
    - 190
    - 750
  title: Московская обл.
-
  code: 
    - 51
  title: Мурманская обл.
-
  code: 
    - 89
  title: Ненецкий автономный округ
-
  code: 
    - 52
    - 152
  title: Нижегородская обл.
-
  code: 
    - 53
  title: Новгородская обл.
-
  code: 
    - 54
    - 154
  title: Новосибирская обл.
-
  code: 
    - 55
  title: Омская обл.
-
  code: 
    - 56
  title: Оренбургская обл.
-
  code: 
    - 57
  title: Орловская обл.
-
  code: 
    - 58
  title: Пензенская обл.
-
  code: 
    - 59
    - 159
    - 81
  title: Пермский край
-
  code: 
    - 25
    - 125
  title: Приморский край
-
  code: 
    - 60
  title: Псковская обл.
-
  code: 
    - 1
  title: Республика Адыгея
-
  code: 
    - 4
  title: Республика Алтай
-
  code: 
    - 3
  title: Республика Бурятия
-
  code: 
    - 5
  title: Республика Дагестан
-
  code: 
    - 6
  title: Республика Ингушетия
-
  code: 
    - 8
  title: Республика Калмыкия
-
  code: 
    - 10
  title: Республика Карелия
-
  code: 
    - 11
    - 111
  title: Республика Коми
-
  code: 
    - 82
  title: Республика Крым
-
  code: 
    - 12
  title: Республика Марий Эл
-
  code: 
    - 13
    - 113
  title: Республика Мордовия
-
  code: 
    - 14
  title: Республика Саха (Якутия)
-
  code: 
    - 15
  title: Республика Северная Осетия - Алания
-
  code: 
    - 16
    - 116
    - 716
  title: Республика Татарстан
-
  code: 
    - 17
  title: Республика Тыва
-
  code: 
    - 19
  title: Республика Хакасия
-
  code: 
    - 61
    - 161
  title: Ростовская обл.
-
  code: 
    - 62
  title: Рязанская обл.
-
  code: 
    - 63
    - 163
  title: Самарская обл.
-
  code: 
    - 64
    - 164
  title: Саратовская обл.
-
  code:
    - 65
  title: Сахалинская обл.
-
  code: 
    - 66
    - 96
    - 196
  title: Свердловская обл.
-
  code: 
    - 67
  title: Смоленская обл.
-
  code: 
    - 26
    - 126
  title: Ставропольский край
-
  code: 
    - 68
  title: Тамбовская обл.
-
  code: 
    - 69
  title: Тверская обл.
-
  code: 
    - 70
  title: Томская обл.
-
  code: 
    - 71
  title: Тульская обл.
-
  code: 
    - 72
  title: Тюменская обл.
-
  code: 
    - 18
  title: Удмуртская Республика
-
  code: 
    - 73
    - 173
  title: Ульяновская обл.
-
  code: 
    - 27
  title: Хабаровский край
-
  code: 
    - 86
    - 186
  title: Ханты-Мансийский автономный округ
-
  code: 
    - 74
    - 174
  title: Челябинская обл.
-
  code: 
    - 20
    - 95
  title: Чеченская Республика
-
  code: 
    - 21
    - 121
  title: Чувашская Республика
-
  code: 
    - 87
  title: Чукотский автономный округ
-
  code: 
    - 76
  title: Ярославская обл.
-
  code: 
    - 0
  title: Не определено